### ISSUE TITLE
State purpose of the repository in README.md

### ISSUE THREAD

**Issue by sigma67** [containerbase/sidecar#273]
It would be helpful for others to know the relationships between the various containerbase/renovate Dockerfiles and images.

To this end it would be great if the README would state what the purpose of this repository is.

(I personally use it as a base to build custom renovate images containing only the tools I need)

**Comment by viceice** [comment]
1. It's directly used by renovate when using `binarySource=docker`.
2. It's the base for https://github.com/renovatebot/base-image, which is the base image for renovate slim and full images.

**Comment by sigma67** [comment]
seems this was done in https://github.com/containerbase/sidecar/pull/277 but not linked here
