### ISSUE TITLE
Missing ci permission

### ISSUE THREAD

**Issue by viceice** [containerbase/sidecar#6]
error: failed to solve: error writing config blob: failed to open writer: unexpected status: 403 Forbidden

/Cc @JamieMagee

**Comment by JamieMagee** [comment]
I suspect we're missing the `packages: write` permission.

**Comment by viceice** [comment]
We need this in all docker image repos, so reopen to track progress centrally.

**Comment by JamieMagee** [comment]
Are all containerbase repos pushing to GHCR? Also I think we need `contents: write` to be able to create releases.

**Comment by viceice** [comment]
Not yet, but planned. Also I plan to create GitHub releases for each version, which hopefully links to official changelogs.

**Comment by viceice** [comment]
Ci still fails
